import Head from 'next/head'
import { Postcard,Categories,PostWidget } from '../Components';


const posts=[
  {title:'React Testing',excerpt:'learn React Testing'},
  {title2:'React Testing',excerpt:'learn React Testing2'},
]
export default function Home() {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <div className='grid grid-cols-1 lg:grid-cols-12 gap-12 '>
          <div className='lg:col-span-4 col-span1'>
            {posts.map((post,index)=>(
            <Postcard post={post} key={post.title}/>
             ))}
          </div>
        <div className='lg:col-span-4 col-span1'>
            <div className='lg:sticky top-8'>
              <PostWidget/>
              <Categories/>
            </div>
        </div>  
       </div>                            
    </div>
  )
}
