import Head from 'next/head'
import { Postcard,Categories,PostWidget } from '../Components';
import { getPosts } from '../services';

export default function Home({posts}) {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>Naqeeb's Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <div className='grid grid-cols-1 lg:grid-cols-12 gap-12 '>
          <div className='lg:col-span-8 col-span1'>
            {posts.map((post,index)=>(
            <Postcard post={post.node} key={post.title}/>
             ))}
          </div>
        <div className='lg:col-span-4 col-span1'>
            <div className='lg:sticky top-8'>
              <PostWidget/>
              <Categories/>
            </div>
        </div>  
       </div>                            
    </div>
  )
}

export async function getStaticProps(){
  const posts= ( await getPosts() ) || [] ;
  return{
    props:{posts}
  }
}
